### ISSUE TITLE
请问支持get请求或post的参数生成随机数或随机字符串吗

### ISSUE THREAD

**Issue by Spillage** [NavInfoNC/visual-wrk#2]
十分感谢大作
研究了下，发现datajson中只能支持已知字符串，请问能不能支持get请求或post的参数生成随机数或随机字符串呢

**Comment by kingsimba** [comment]
目前我们的用法是先用python等方式，生成一个比较大的json案例库。并没有动态生成的能力。
你觉得这个方式不够方便吗？希望在案例库中支持一些随机函数？比如rand(1,100)？还是想支持任意自定义函数？

**Comment by Spillage** [comment]
实际上，可能什么都有…………我想到别的办法了，谢谢
