### ISSUE TITLE
再请问下，我在macOS上安装失败，求教

### ISSUE THREAD

**Issue by Spillage** [NavInfoNC/visual-wrk#3]
➜  visual-wrk git:(master) ✗ make          
Building LuaJIT...
==== Building LuaJIT 2.1.0-beta3 ====
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src
LINK      luajit
ld: can't open output file for writing: luajit, errno=13 for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Mojav
10.14.5 (18F132)
……………………

**Comment by zhaoguangqiang** [comment]
这块我们还没有对Mac平台做过适配，现在只在Linux上适配过，不过如果你感兴趣，可以在Mac平台解决一下这个问题

**Comment by Spillage** [comment]
谢谢回复，在mac上解决了
