### ISSUE TITLE
Number of Threads

### ISSUE THREAD

**Issue by brunobritodev** [NavInfoNC/visual-wrk#5]
Hi!

Awesome project, congratulations!!

I've a doubt, visual-wrk uses threads? The wrk has the -t parameter. Could you explain how visual-wrk make the requests?

**Comment by zhaoguangqiang** [comment]
Visual-wrk also use the threads and the thread is used in the same way as wrk. The difference is visual-wrk not use -t parameter, the number of threads is determined by the number of local cpu cores.The make requests method also same as wrk.
